spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 10000
      max-lifetime: 30000
      pool-name: HikariCP
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate