spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#  web:
#    cors:
#      allowed-origins: "https://restapi-production-bradesco.up.railway.app"
#      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
#      allowed-headers: "*"
#      allow-credentials: true
#server:
#  forward-headers-strategy: framework
