spring:
  datasource:
    url: jdbc:h2:mem:bootcamp2025
    username: bootcamp2025
    password:
  jpa:
    show-sql: true #query verbosa no console
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false